version: '3'

services:
  mysqldb:
    image : mysql:latest
    container_name : db2
    volumes :
#      - mysql-data:/var/lib/mysql
      - ./mysql-datab:/var/lib/mysql
    environment :
      MYSQL_USER : ${db_user}
      MYSQL_ROOT_PASSWORD : ${root_pwd}
      MYSQL_PASSWORD : ${db_password}
      MYSQL_DATABASE : ${db_name}
      

  web1 :
    image : railsapp
    command : "rails server -b 0.0.0.0"
    environment :
      RAILS_ENV : ${app_env}

    depends_on :
      - mysqldb
      
      
  web2 :
    image : railsapp
    command : "rails server -b 0.0.0.0"
    environment :
      RAILS_ENV : ${app_env}
    depends_on :
      - mysqldb


  web3 :
    image : railsapp
    command : "rails server -b 0.0.0.0"
    environment :
      RAILS_ENV : ${app_env}
    depends_on :
      - mysqldb

      
  nginx :
    image : nginx:latest
    volumes : 	
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on :
      - web1
      - web2
      - web3
    ports :
      - "8080:80" 

#volumes:
#    mysql-data :
